#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-or-later
USE_PROCD=1
START=94
STOP=11

start_service() {
	procd_open_instance qcontrol
	procd_set_param command /usr/sbin/qcontrol -f -c /etc/qcontrol.conf
	procd_set_param respawn
	procd_close_instance
	procd_open_instance firmware
	procd_set_param command /usr/sbin/firmware-install check
	procd_close_instance
	tr '\000' '\n' < /proc/device-tree/compatible | grep -qx 'fujitsu,q703' || return 0
	procd_open_instance leds
	procd_set_param command /usr/sbin/q703-leds
	procd_set_param respawn
	procd_close_instance
}
